# Generated by Django 3.2.12 on 2022-11-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESC_KOR', models.CharField(max_length=200)),
                ('SERVING_WT', models.CharField(max_length=50)),
                ('NUTR_CONT1', models.CharField(max_length=50)),
                ('NUTR_CONT2', models.CharField(max_length=50)),
                ('NUTR_CONT3', models.CharField(max_length=50)),
                ('NUTR_CONT4', models.CharField(max_length=50)),
                ('NUTR_CONT5', models.CharField(max_length=50, null=True)),
                ('NUTR_CONT6', models.CharField(max_length=50, null=True)),
                ('NUTR_CONT7', models.CharField(max_length=50, null=True)),
                ('NUTR_CONT8', models.CharField(max_length=50, null=True)),
                ('NUTR_CONT9', models.CharField(max_length=50, null=True)),
                ('ANIMAL_PLANT', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
